### PR TITLE
Pymysql fix

### LINKED ISSUE #882: PyMySQL version 0.10 produces ImportError crash on mycli execution
After updating PyMySQL from 0.9.3 to 0.10.0 the following crash occurs when executing mycli (version 1.12.1):

```
Traceback (most recent call last):
  File "/usr/bin/mycli", line 33, in <module>
    sys.exit(load_entry_point('mycli==1.21.1', 'console_scripts', 'mycli')())
  File "/usr/bin/mycli", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/<user>/.local/lib/python3.8/site-packages/mycli/main.py", line 41, in <module>
    from .sqlexecute import FIELD_TYPES, SQLExecute
  File "/home/<user>/.local/lib/python3.8/site-packages/mycli/sqlexecute.py", line 6, in <module>
    from pymysql.converters import (convert_mysql_timestamp, convert_datetime,
ImportError: cannot import name 'convert_mysql_timestamp' from 'pymysql.converters' (/home/<user>/.local/lib/python3.8/site-packages/pymysql/converters.py)
```

I downgraded to PyMySQL 0.9.3 to continue using mycli

### LINKED ISSUE #884: cannot import name 'convert_mysql_timestamp' from 'pymysql.converters'
while typing `mycli` command in the terminal, it displays a lot errers:
```
PS C:\Users\leon> mycli
Traceback (most recent call last):
  File "D:\Python\Python38-32\Scripts\mycli-script.py", line 11, in <module>
    load_entry_point('mycli==1.21.1', 'console_scripts', 'mycli')()
  File "d:\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "d:\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "d:\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2462, in load
    return self.resolve()
  File "d:\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "d:\python\python38-32\lib\site-packages\mycli-1.21.1-py3.8.egg\mycli\main.py", line 41, in <module>
    from .sqlexecute import FIELD_TYPES, SQLExecute
  File "d:\python\python38-32\lib\site-packages\mycli-1.21.1-py3.8.egg\mycli\sqlexecute.py", line 6, in <module>
    from pymysql.converters import (convert_mysql_timestamp, convert_datetime,
ImportError: cannot import name 'convert_mysql_timestamp' from 'pymysql.converters' (d:\python\python38-32\lib\site-packages\pymysql\converters.py)
```

### enviroment:
win10 pro
```
PS C:\Users\leon> python -V
Python 3.8.4
```
```
mysql> status
--------------
C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe  Ver 8.0.21 for Win64 on x86_64 (MySQL Community Server - GPL)

Connection id:          8
Current database:
Current user:           root@localhost
SSL:                    Cipher in use is TLS_AES_256_GCM_SHA384
Using delimiter:        ;
Server version:         8.0.21 MySQL Community Server - GPL
Protocol version:       10
Connection:             localhost via TCP/IP
Server characterset:    utf8mb4
Db     characterset:    utf8mb4
Client characterset:    gbk
Conn.  characterset:    gbk
TCP port:               3306
Binary data as:         Hexadecimal
Uptime:                 4 hours 34 min 42 sec

Threads: 2  Questions: 5  Slow queries: 0  Opens: 115  Flush tables: 3  Open tables: 36  Queries per second avg: 0.000
--------------

mysql>
```

### what I have tried
I've use pip command to uninstall and reinstall `mycli`, but theres' still the same error
not sure what to do now...

### PR DESCRIPTION
**Pull request by amjith**
## Description
Fixes #884 
Fixes #882

### CODE REVIEW

**Comment by pasenor** [comment]
Another [change in PyMySQL](https://github.com/PyMySQL/PyMySQL/issues/803): they now append `e0` to all floats, like `0.5e0`. In mycli, it only affects `sql-*` formatters. 
Are we fine with this new behavior? For now I just fixed the failing test to reflect it.

**Comment by amjith** [comment]
If we hear complaints about the e0 at the end we can work on fixing that.
