### ISSUE TITLE
PyMySQL version 0.10 produces ImportError crash on mycli execution

### ISSUE THREAD

**Issue by lukexorz** [dbcli/mycli#882]
After updating PyMySQL from 0.9.3 to 0.10.0 the following crash occurs when executing mycli (version 1.12.1):

```
Traceback (most recent call last):
  File "/usr/bin/mycli", line 33, in <module>
    sys.exit(load_entry_point('mycli==1.21.1', 'console_scripts', 'mycli')())
  File "/usr/bin/mycli", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/<user>/.local/lib/python3.8/site-packages/mycli/main.py", line 41, in <module>
    from .sqlexecute import FIELD_TYPES, SQLExecute
  File "/home/<user>/.local/lib/python3.8/site-packages/mycli/sqlexecute.py", line 6, in <module>
    from pymysql.converters import (convert_mysql_timestamp, convert_datetime,
ImportError: cannot import name 'convert_mysql_timestamp' from 'pymysql.converters' (/home/<user>/.local/lib/python3.8/site-packages/pymysql/converters.py)
```

I downgraded to PyMySQL 0.9.3 to continue using mycli

**Comment by lukexorz** [comment]
This looks like the commit that removed the convert_mysql_timestamp function:
https://github.com/PyMySQL/PyMySQL/commit/fe0cd60e6f9e3bc0fb81f76f7e4fa30a1e1b34cc#diff-40496cc4a0f4db6907de60f7ce470b95

**Comment by lunatiee** [comment]
solution 1)  Install PyMySQL 0.9.2 (this is last version that you can use with mycli)

or

solution 2)  
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mycli/sqlexecute.py

**Open the above file and modify it as follows:**

line 6) from pymysql.converters import (convert_datetime, 
line 102) FIELD_TYPE.TIMESTAMP: lambda obj: (convert_datetime(obj) or obj),

**Comment by fraoustin** [comment]
If you want to use the last version of mycli, you can use mycli with docker https://hub.docker.com/repository/docker/dbcliorg/mycli

**Comment by artfulrobot** [comment]
I was new to doing this, so in case it helps anyone else, these are the commands I used to get it working based on @lunatiee 's solution ➊

```bash
$ pip3 install mycli
$ pip3 install -I PyMySQL==0.9.2
```

**Comment by amjith** [comment]
We have a sprint this weekend and we'll see if we can tackle this issue during the sprint. 

If anyone is interested in participating, we're doing a virtual sprint through the PyOhio conference. https://www.pyohio.org/2020/events/sprints

**Comment by ZDSDESIRE** [comment]
> solution 1) Install PyMySQL 0.9.2 (this is last version that you can use with mycli)
> 
> or
> 
> solution 2)
> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mycli/sqlexecute.py
> 
> **Open the above file and modify it as follows:**
> 
> line 6) from pymysql.converters import (convert_datetime,
> line 102) FIELD_TYPE.TIMESTAMP: lambda obj: (convert_datetime(obj) or obj),

This is an effective solution.

**Comment by amjith** [comment]
It's fixed in the latest version. Please update.

pip install -U mycli

**Comment by artfulrobot** [comment]
yay, it works again. THANKS ALL!

**Comment by verajosemanuel** [comment]
not working even with the latest version in Cent Os

**Comment by ZDSDESIRE** [comment]
Not working even with the latest version in Win10: 
```text
Successfully installed mycli-1.22.1 prompt-toolkit-3.0.5

C:\Users\z_zon>mycli --help
Traceback (most recent call last):
  File "e:\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Python\Python38\Scripts\mycli.exe\__main__.py", line 4, in <module>
  File "e:\python\python38\lib\site-packages\mycli\main.py", line 9, in <module>
    from pwd import getpwuid
ModuleNotFoundError: No module named 'pwd'
```
I returned to mycli-1.21.1 and get it working based on @lunatiee 's solution ②: https://github.com/dbcli/mycli/issues/882#issuecomment-660885896

**Comment by amjith** [comment]
@verajosemanuel Can you tell me what is the version you're using? If you installed it via `yum` the latest version is probably not available via yum. 

You need to install it via `pip`.

**Comment by amjith** [comment]
@ZDSDESIRE I can't reproduce it. Looks like the error you're seeing is very different from the original error reported. 

Looks like there is an issue with your python installation. The module not found error is complaining about a module called `pwd` but this is a standard library module that is shipped with python. https://docs.python.org/3.8/library/pwd.html

You might want to reinstall python on your machine and try again.

**Comment by thorstenkampe** [comment]
@amjith `pwd` is Unix-only:
> This module provides access to the Unix user account and password database. It is available on all Unix versions.

**Comment by thorstenkampe** [comment]
Looks like the developers are only testing on Linux or MacOS. On Windows `mycli` is completely broken because of the import of `pwd`.

**Comment by amjith** [comment]
You're right. I'm sorry. I didn't know that pwd is Unix only. I'll have to
address this.

**Comment by amjith** [comment]
@thorstenkampe @ZDSDESIRE I'v created a branch that fixes the `pwd` import issue. 

Can you try it out? 

```
pip install -U https://github.com/dbcli/mycli/archive/pwd_optional.zip
```

**Comment by thorstenkampe** [comment]
@amjith seems to work fine

**Comment by verajosemanuel** [comment]
ERROR: Package 'mycli' requires a different Python: 2.7.5 not in '>=3.6'

**Comment by ZDSDESIRE** [comment]
@amjith 
Yay, it's working, thanks! Have you pulled out the pwd module?
